### PR TITLE
Mark release `1.0.0`

### PR DESCRIPTION
**Pull request by wyrzyk**
By approving the PR, you're approving the `1.0.0` API. I will merge it after the release.

- [x] Release `db-replica` 1.0.0 first
- [ ] Make sure Aurora LSN can be implemented with the current version of `ReplicaConsistency`

### CODE REVIEW

**Comment by dagguh** [comment]
> Make sure Aurora LSN can be implemented with the current version of `ReplicaConsistency`

It's a nice-to-have, but not a must. We can release 2.0.0.

**Review by dagguh — APPROVED** [review]
I'm ok with the current API, whatever flaws it might have. It's because [it's already on prod for a few releases already, so it should have been 1.0.0 for quite a while now](https://semver.org/#how-do-i-know-when-to-release-100).

**Comment by wyrzyk** [comment]
> I'm ok with the current API, whatever flaws it might have. It's because it's already on prod for a few releases already, so it should have been 1.0.0 for quite a while now.

My only concern is that the only `ReplicaConsistency` implementation we were using is clock based and we don't consider it prod ready. But you're right we can release `2.0.0`.

**Comment by wyrzyk** [comment]
https://packages.atlassian.com/maven-external/com/atlassian/db/replica/db-replica/1.0.0/

**Pull request merged**
